version: '3.9'
services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: devdb
        ports:
            - "3306:3306"
        volumes:
            - mysql:/`var`/lib/mysql

volumes:
    mysql: